Revert "Added support for WakeLock Toggles"
This reverts commit 8ba2cc0fe2a61c95178294b09974da49e657dcc5.

This is a temp. revert and might be added back later, due to:
drivers/base/power/wakeup.c:440:2: error: implicit declaration of function 'wakeup_source_not_registered' [-Werror=implicit-function-declaration]
  if (WARN(wakeup_source_not_registered(ws),
  ^
cc1: some warnings being treated as errors