Revert "regulator: qpnp-regulator: Use power efficient workqueue"
This reverts commit eed55195012cc8fdd37da4b33862848538f3069f.

Revert due to:
drivers/regulator/qpnp-regulator.c: In function 'qpnp_regulator_vs_ocp_isr':
drivers/regulator/qpnp-regulator.c:1107:22: error: 'system_power_efficient_wq' undeclared (first use in this function)
   queue_delayed_work(system_power_efficient_wq,
drivers/regulator/qpnp-regulator.c:1107:22: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:308: recipe for target 'drivers/regulator/qpnp-regulator.o' failed
make[3]: *** [drivers/regulator/qpnp-regulator.o] Error 1